version: "3"
services:
  nginx:
    container_name: nginx
    network_mode: host
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/certs:/etc/certs:z
      - ./conf:/etc/nginx/conf.d:z
      - ./public:/usr/share/nginx/html:z
